version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/SerilogTraceListener.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: kWjkVgz/CQ1uUURl33OhzTbq/MB35u24/uLXntDcxoXDJD1lXjozxqeNiupqxG2E
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
